### ISSUE TITLE
Support for Change Stream DDL

### ISSUE THREAD

**Issue by rob-pomelo** [daichirata/hammer#41]
Spanner recently added change streams (https://cloud.google.com/spanner/docs/change-streams/manage). Right now using the library on our schema fails because of unknown DDL (essentially because of `CREATE CHANGE STREAM GlobalChangeStream FOR All;`). Even being able to just ignore it would be great.

Thanks for an awesome library!

**Comment by daichirata** [comment]
Thanks for the report. We would like to support it in the future, but it is difficult to support the change streams definition immediately in hammer. So I added the ignore-change-streams flag you suggested. By specifying this flag, we can temporarily ignore the `CREATE CHANGE STREAM` definition.

**Comment by rob-pomelo** [comment]
Wow thank you so much for the quick turn around, super appreciated!
