### ISSUE TITLE
Version command for hammer

### ISSUE THREAD

**Issue by hhanda** [daichirata/hammer#44]
It would be great if hammer app could include an additional command of something like `hammer -v` or `hammer version` or something on the similar lines, to be able identify which version the executable is on, if there already exists one such command or option, please feel free to close this ticket but do give reference for the same, since it gets tricky once the executable is moved out of it source directory.

**Comment by daichirata** [comment]
Thanks for the suggestion to add the feature. We have added the `hammer version` command in v0.5.12.
