### ISSUE TITLE
Support timestamp functions

### ISSUE THREAD

**Issue by hamoelze** [daichirata/hammer#45]
Hello,
On `hammer apply` or `hammer diff`, while creating a table with a generated column using a timestamp function, such as:
```
CREATE TABLE examples (
  inserted_at TIMESTAMP  NOT NULL,
  examples_id STRING(36) NOT NULL,
  examples_timestamp TIMESTAMP  AS(TIMESTAMP_ADD(inserted_at, INTERVAL 1 DAY)) STORED
) PRIMARY KEY(examples_id);
```

produces the following error:
`Error: spanner://projects/test-project/instances/test-instance/databases/example_dev failed to parse ddl: spanner://projects/test-project/instances/test-instance/databases/example_dev:4: got "1", want ")" or ","`

**Comment by neglect-yp** [comment]
related issue: https://github.com/googleapis/google-cloud-go/issues/6949
